### ISSUE TITLE
each() function is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by swapteam** [mikepultz/netdns2#83] opened 2018-01-23 12:13 UTC
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in F:\upupw\vhosts\127.0.0.10\vendor\pear\net_dns2\Net\DNS2.php on line 923

**Comment by mikepultz** [comment] 2018-01-23 14:29
Duplicate of #79 - will be fixed in the next release.

**Closed by mikepultz** 2018-01-23 14:29 UTC
